### ISSUE TITLE
Uncaught ReferenceError: fs is not defined

### ISSUE THREAD

**Issue by TerenceBlevins** [WispOfTheWinds/pandocia#1]
[Enter steps to reproduce:]

1. installed panocia
2. ran panocia from Atom on a ".docx" file in buffer
3. convert failed

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [pandocia](https://github.com/WispOfTheWinds/pandocia) package 0.1.0

### Stack Trace

Uncaught ReferenceError: fs is not defined

```
At C:\Users\Terry\.atom\packages\pandocia\lib\pandocia.js:57

ReferenceError: fs is not defined
    at Object.convert (/packages/pandocia/lib/pandocia.js:57:25)
    at /packages/pandocia/lib/pandocia.js:41:39)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:349290)
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:699460)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:875983)
    at SelectListView.didClickItem (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:873925)
    at ListItemView.onclick (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:872915)
    at ListItemView.didClick (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:877003)
```

### Commands

```
  2x -9:04.1.0 pandoc-preview:show (input.hidden-input)
 36x -7:13.9.0 core:move-left (input.hidden-input)
  5x -7:09.2.0 core:delete (input.hidden-input)
     -7:04.9.0 core:confirm (input.hidden-input)
  4x -6:54.5.0 pandoc-preview:show (input.hidden-input)
  3x -4:00.8.0 asciidoc-preview:toggle (ul.list-inline.tab-bar.inset-panel)
     -0:37 command-palette:toggle (input.hidden-input)
     -0:29.3.0 pandocia:convert (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-assistant 0.2.3 
asciidoc-image-helper 1.0.1 
asciidoc-preview 2.13.1 
autocomplete-asciidoc 0.1.2 
language-asciidoc 1.11.0 
pandoc 0.2.2 
pandoc-convert 1.1.1 
pandocia 0.1.0 
```

**Comment by WispOfTheWinds** [comment]
Sorry I ended up not seeing this! Just peeking at it, I'm almost certain it's an issue with the path separator on Windows (`/` vs. `\`). I'll take a look at it tomorrow after I get some sleep in!

Note to self: use `path.sep` to make it play nice
